#!/usr/bin/perl
# po2json
# Copyright (C) Eskild Hustvedt 2010
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

use strict;
use warnings;
use Locale::PO qw(encode_json);
use JSON;
use Data::Dumper qw(Dumper);

my $infile = shift;
my $outfile = shift;

my $f = Locale::PO->load_file_asarray($infile);

my %map;

foreach my $o (@{$f})
{
	next if $o->loaded_line_number < 6;
	my $id  = $o->dequote($o->msgid);
	my $str = $o->dequote($o->msgstr);
	$map{$id} = $str;
}

open(my $out,'>',$outfile);
print {$out} encode_json(\%map);
close($out);

exit(0);

sub slurp
{
	my $f = shift;
	open(my $in,'<',$f);
	local $/;
	$/ = undef;
	my $data = <$in>;
	close($in);
	return $data;
}

sub usage
{
	print "USAGE: $0 outfile.pot infile1.js infile2.js ..\n";
}
